import { Config } from "effect"

export function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

const copy = process.env["PRIVACYCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]
const fff = process.env["PRIVACYCODE_DISABLE_FFF"]

function enabledByExperimental(key: string) {
  return process.env[key] === undefined ? truthy("PRIVACYCODE_EXPERIMENTAL") : truthy(key)
}

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  PRIVACYCODE_AUTO_HEAP_SNAPSHOT: truthy("PRIVACYCODE_AUTO_HEAP_SNAPSHOT"),
  PRIVACYCODE_GIT_BASH_PATH: process.env["PRIVACYCODE_GIT_BASH_PATH"],
  PRIVACYCODE_CONFIG: process.env["PRIVACYCODE_CONFIG"],
  PRIVACYCODE_CONFIG_CONTENT: process.env["PRIVACYCODE_CONFIG_CONTENT"],
  PRIVACYCODE_DISABLE_AUTOUPDATE: truthy("PRIVACYCODE_DISABLE_AUTOUPDATE"),
  PRIVACYCODE_ALWAYS_NOTIFY_UPDATE: truthy("PRIVACYCODE_ALWAYS_NOTIFY_UPDATE"),
  PRIVACYCODE_DISABLE_PRUNE: truthy("PRIVACYCODE_DISABLE_PRUNE"),
  PRIVACYCODE_DISABLE_TERMINAL_TITLE: truthy("PRIVACYCODE_DISABLE_TERMINAL_TITLE"),
  PRIVACYCODE_SHOW_TTFD: truthy("PRIVACYCODE_SHOW_TTFD"),
  PRIVACYCODE_DISABLE_AUTOCOMPACT: truthy("PRIVACYCODE_DISABLE_AUTOCOMPACT"),
  PRIVACYCODE_DISABLE_MODELS_FETCH: truthy("PRIVACYCODE_DISABLE_MODELS_FETCH"),
  PRIVACYCODE_DISABLE_MOUSE: truthy("PRIVACYCODE_DISABLE_MOUSE"),
  PRIVACYCODE_FAKE_VCS: process.env["PRIVACYCODE_FAKE_VCS"],
  PRIVACYCODE_SERVER_PASSWORD: process.env["PRIVACYCODE_SERVER_PASSWORD"],
  PRIVACYCODE_SERVER_USERNAME: process.env["PRIVACYCODE_SERVER_USERNAME"],
  PRIVACYCODE_DISABLE_FFF: fff === undefined ? process.platform === "win32" : truthy("PRIVACYCODE_DISABLE_FFF"),

  // Experimental
  PRIVACYCODE_EXPERIMENTAL_FILEWATCHER: Config.boolean("PRIVACYCODE_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  PRIVACYCODE_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("PRIVACYCODE_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  PRIVACYCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("PRIVACYCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  PRIVACYCODE_MODELS_URL: process.env["PRIVACYCODE_MODELS_URL"],
  PRIVACYCODE_MODELS_PATH: process.env["PRIVACYCODE_MODELS_PATH"],
  PRIVACYCODE_DB: process.env["PRIVACYCODE_DB"],

  PRIVACYCODE_WORKSPACE_ID: process.env["PRIVACYCODE_WORKSPACE_ID"],
  PRIVACYCODE_EXPERIMENTAL_WORKSPACES: enabledByExperimental("PRIVACYCODE_EXPERIMENTAL_WORKSPACES"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get PRIVACYCODE_DISABLE_PROJECT_CONFIG() {
    return truthy("PRIVACYCODE_DISABLE_PROJECT_CONFIG")
  },
  get PRIVACYCODE_EXPERIMENTAL_REFERENCES() {
    return enabledByExperimental("PRIVACYCODE_EXPERIMENTAL_REFERENCES")
  },
  get PRIVACYCODE_TUI_CONFIG() {
    return process.env["PRIVACYCODE_TUI_CONFIG"]
  },
  get PRIVACYCODE_CONFIG_DIR() {
    return process.env["PRIVACYCODE_CONFIG_DIR"]
  },
  get PRIVACYCODE_PURE() {
    return truthy("PRIVACYCODE_PURE")
  },
  get PRIVACYCODE_PERMISSION() {
    return process.env["PRIVACYCODE_PERMISSION"]
  },
  get PRIVACYCODE_PLUGIN_META_FILE() {
    return process.env["PRIVACYCODE_PLUGIN_META_FILE"]
  },
  get PRIVACYCODE_CLIENT() {
    return process.env["PRIVACYCODE_CLIENT"] ?? "cli"
  },
}
